---
title: "Code"
author: "LR"
date: '2022-06-28'
output: html_document
---

The code of the following chunck merges the various datasheets of my relational database to create a final wide whole datasheet.

```{r}
library(readr)
library(dplyr)
study_details <- read_csv("Data/study_details.csv")
species_info <- read_csv("Data/species_info.csv")
pfas_info <- read_csv("Data/pfas_info.csv")
cohort_info <- read_csv("Data/cohort_info.csv")
sample_info <- read_csv("Data/sample_info.csv")
measurement <- read_csv("Data/measurement.csv")
combined <- inner_join(measurement, sample_info, by = "Sample_ID")
combined <- inner_join(combined, cohort_info, by = "Cohort_ID")
combined <- inner_join(combined, study_details, by = "Study_ID")
combined <- inner_join(combined, pfas_info, by = "pfas_ID")
combined <- inner_join(combined, species_info, by = "Species_ID")
data_combined <- combined %>% 
  select(-c(Timestamp.x, Timestamp.y, Timestamp.x.x, Timestamp.y.y, Timestamp.x.x.x, Timestamp.y.y.y))
View(data_combined)
```
Create a new dataframe without not necessary data for MTR calculation:

```{r}
data_MTR <- data_combined %>%
  select(Measurement_ID, Sample_ID, pfas_ID, Mean, SE, SD, N, group_info, Cohort_ID, Sample_type, Species_ID, Study_ID)
```
Remove S_002 because it doesn't have clear data yet

```{r}
data_MTR <- data_MTR %>%
  filter(Study_ID != "S_002")
```
Overall meta-analytic mean calculation:
```{r}

```

